# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('count_of_containers', models.IntegerField()),
                ('choose_language', models.CharField(max_length=30)),
                ('code', models.TextField()),
            ],
        ),
    ]
